apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: chatsphere
  labels:
    app.kubernetes.io/name: chatsphere
    app.kubernetes.io/component: backend
data:
  LISTEN_ADDR: ":8080"
  REDIS_ADDR: "redis:6379"
